/**
 * Antigravity Rules Generator (.antigravity/rules/ai_policy.md)
 */

export function generateAntigravityConfig({ env, assignments, timestamp = new Date().toISOString() }) {
  const archModel = assignments.ARCHITECTURE?.assignedModelName || 'Gemini 3 Pro';
  const fastModel = assignments.RAPID_FIX?.assignedModelName || 'Gemini 3.8 Flash';

  return `<!-- AUTO-GENERATED BY AI-GOVERNOR | ${timestamp} -->
# Antigravity Agent Guidelines & Model Governance

## 1. Role & Identity in this Project
You are operating within a project governed by **ai-governor**.
- Your Primary Domain: **Architecture, Codebase Research & Rapid Dispatch**
- Assigned Architecture Model: **${archModel}** (Reasoning Intensity: **MAX_THINKING**)
- Assigned Rapid Iteration Model: **${fastModel}** (Reasoning Intensity: **ECO_FAST**)

## 2. Planning Mode & Artifact Enforcement
- For any change affecting $>2$ files, you **MUST** create/update \`implementation_plan.md\` before modifying code.
- Utilize your large context window (1M-2M tokens) for complete codebase audits rather than guessing.
- Delegate isolated research or long file reading to subagents to keep context clean.

## 3. 🔴 STRICT HUMAN APPROVAL GATES
Obtain explicit user confirmation before:
1. Mutating database schemas or running migrations.
2. Installing new npm dependencies (verify with registry tools first).
3. Modifying authentication, credentials, or \`.env\` variables.
4. Performing git push or altering git history.

## 4. Anti-Hallucination & Quality Protocol
- Always run \`find_by_name\` or \`grep_search\` to verify symbols/files exist.
- Never invent external package imports.
- Always provide command-line test execution proof before concluding a task.
`;
}
