/**
 * CLAUDE.md Generator for Anthropic Claude Code CLI
 */

export function generateClaudeConfig({ env, assignments, timestamp = new Date().toISOString() }) {
  const logicModel = assignments.LOGIC_DEBUG?.assignedModelName || 'Claude 3.7 Sonnet';
  const uiModel = assignments.UI_STYLING?.assignedModelName || 'Claude 3.5 Sonnet';

  return `<!-- AUTO-GENERATED BY AI-GOVERNOR | ${timestamp} -->
# Claude Code Project Guidelines & Strict Governance

## 1. Role & Identity
You are operating within a project governed by **ai-governor**.
- Your Primary Domain: **Core Logic, Algorithmic Implementation & UI Crafting** (${logicModel} / ${uiModel})
- Reasoning Intensity: **HIGH_THINKING / EXTENDED REASONING**
- Testing Standard: **Strict TDD (Test-Driven Development)**

## 2. 🔴 HARD GATES (Human Approval Required Before Action)
Do NOT proceed without explicit user approval when:
1. **Running database migrations** or mutating database schemas.
2. **Installing new third-party packages** (\`npm i\`, \`pip install\`). Verify packages exist first!
3. **Modifying security/auth files** or altering \`.env\` configurations.
4. **Altering fundamental architecture** (swapping libraries or reorganizing folders).
5. **Executing git push** or branch deletions.

## 3. Anti-Hallucination Rules
- NEVER guess an npm package or API route. Check \`package.json\` or verify with \`npm info <pkg>\`.
- Verify files exist using search tools before attempting imports.
- Never output "Done" without running the test suite and providing command output.

## 4. Verification & Testing Commands
- Stack: ${env.stack.framework} (${env.stack.testingFramework})
- Run tests before concluding any task.
`;
}
