/**
 * .cursorrules Generator for Cursor / Windsurf
 */

export function generateCursorConfig({ env, assignments, timestamp = new Date().toISOString() }) {
  return `<!-- AUTO-GENERATED BY AI-GOVERNOR | ${timestamp} -->
# Cursor Rules - AI Policy Compliance

## Project Stack: ${env.stack.framework} (${env.stack.testingFramework})

## 1. Operating Rules
- Strictly follow TDD: Write or verify tests before finishing fixes.
- Do not make architectural changes without prior confirmation.

## 2. 🔴 Mandatory Human Approvals
- Never install packages without user request.
- Never modify database schemas or .env files without explicit instruction.
- Never run destructive git commands.

## 3. Anti-Hallucination
- Check existing codebase patterns before suggesting new abstractions.
`;
}
