/**
 * Master AI_POLICY.md Generator
 */

import { HUMAN_CLEARANCE_MATRIX } from '../rbac.js';

export function generateMasterPolicy({ env, assignments, registry, timestamp = new Date().toISOString() }) {
  const activeIDEsList = env.ides.map(i => `${i.name} (${i.reason})`).join(', ') || 'Standard Terminal Environment';
  
  let content = `# 🛡️ PROJECT AI GOVERNANCE & EXECUTION POLICY
> **Auto-generated by \`ai-governor\`** on \`${timestamp}\`  
> **Active Environment Detected:** ${activeIDEsList}  
> **Available Models:** ${env.availableModels.join(', ')}

---

## 1. Executive Summary & Core Rules
This project enforces **Strict Role-Based Access Control (RBAC)** on all AI tools and models.
1. **NO BLIND CODE:** An architectural implementation plan is mandatory before any multi-file change.
2. **PROOF OF WORK:** No task is complete without running verification tests and displaying command output.
3. **HUMAN APPROVAL GATEWAYS:** Critical actions (database, auth, new packages) are strictly gated.

---

## 2. Model Task Assignments & Reasoning Intensity

The following models are assigned to specific disciplines based on current benchmark scores and local availability:

| Task Discipline | Assigned Model | Intensity Budget | Clearance Level | Fallback Model |
| :--- | :--- | :--- | :--- | :--- |
`;

  for (const item of Object.values(assignments)) {
    content += `| **${item.domainTitle}** | \`${item.assignedModelName}\` | **${item.intensity}** | \`${item.clearance}\` | \`${item.fallbackModelId}\` |\n`;
  }

  content += `
---

## 3. Strict Model Scopes & Constraints

`;

  for (const item of Object.values(assignments)) {
    content += `### ${item.domainTitle} (\`${item.assignedModelName}\` - Intensity: ${item.intensity})
* **Allowed Actions:**
${item.allowedActions.map(a => `  - ${a}`).join('\n')}
* **Forbidden Actions:**
${item.forbiddenActions.map(f => `  - ❌ ${f}`).join('\n')}

`;
  }

  content += `---

## 4. Human-in-the-Loop Clearance Matrix

The AI **MUST** observe the following boundary levels:

### 🔴 RED LEVEL: STRICT HARD STOP (Human Permission Mandatory)
The AI must **stop, present the proposal, and await explicit human approval** before executing:
${HUMAN_CLEARANCE_MATRIX.RED.triggers.map(t => `- **${t}**`).join('\n')}

### 🟡 YELLOW LEVEL: NOTICE & LOG (Autonomous with Notice)
The AI may proceed autonomously, but must explicitly flag the change in its summary:
${HUMAN_CLEARANCE_MATRIX.YELLOW.triggers.map(t => `- ${t}`).join('\n')}

### 🟢 GREEN LEVEL: FULL AUTONOMY
The AI executes freely without asking:
${HUMAN_CLEARANCE_MATRIX.GREEN.triggers.map(t => `- ${t}`).join('\n')}

---

## 5. Anti-Hallucination Guardrails
1. **Never guess npm packages:** Always check \`package.json\` or verify with \`npm info <package>\` before importing any library.
2. **Never guess API routes:** Inspect backend route definitions or OpenAPI schemas before calling external or internal endpoints.
3. **Never guess file paths:** Use search tools (\`grep\`, \`find\`) to confirm a file exists before referencing it.
4. **Never claim completion without proof:** Include raw terminal test outputs in the response.

---
*Generated with [ai-governor](https://github.com/alishba/ai-governor)*
`;

  return content;
}
